const constants = {
    FETCH_EMAIL_REQUEST: "FETCH_EMAIL_REQUEST",
    FETCH_EMAIL_SUCCESS: "FETCH_EMAIL_SUCCESS",
    ONCHANGE_EVENT:"ONCHANGE_EVENT",
    ON_NAME_SUBMIT:"ON_NAME_SUBMIT",
    ON_NAME_SUBMIT_SUCCESS:"ON_NAME_SUBMIT_SUCCESS",
    ON_VALIDATE:"ON_VALIDATE",
    ON_VALID_SUCCESS:"ON_VALID_SUCCESS",
    ON_REQUEST_DATA:"ON_REQUEST_DATA",
    ON_REQUEST_DATA_SUCCESS:"ON_REQUEST_DATA_SUCCESS"
  };
  
  export default constants;
  