const constants = {
    FETCH_EMAIL_REQUEST: "FETCH_EMAIL_REQUEST",
    FETCH_EMAIL_SUCCESS: "FETCH_EMAIL_SUCCESS",
    ONCHANGE_EVENT:"ONCHANGE_EVENT",
    ON_NAME_SUBMIT:"ON_NAME_SUBMIT",
    ON_NAME_SUBMIT_SUCCESS:"ON_NAME_SUBMIT_SUCCESS"
  };
  
  export default constants;
  